In [11]:
# 2d lists: list of lists
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
for row in a:
    for col in row:
        print(col, end=" ")
# get number 6
print(a[1][2])
# print 2 nd row
print(a[1])
#clicing same as 1d list
print(a[1:3])
print(a[1])
print(a[1:2])

1 2 3 4 5 6 7 8 9 6
[4, 5, 6]
[[4, 5, 6], [7, 8, 9]]
[4, 5, 6]
[[4, 5, 6]]


In [13]:
student_grades = [['john', 7.5], ['Mary', 9.0], ['Bob', 6.0], ['Alice', 8.0], ['Mike', 4.0], ['Anna', 10.0], ['Tom', 5.0], ['Peter', 3.5], ['Jane', 9.5], ['Jack', 6.5]]

In [16]:
# print disctintion students who have grade >= 8.0
for student in student_grades:
    if student[1] >= 8.0:
        print(f'Name: {student[0]}, Grade: {student[1]}')

Name: Mary, Grade: 9.0
Name: Alice, Grade: 8.0
Name: Anna, Grade: 10.0
Name: Jane, Grade: 9.5


In [15]:
# Count how many passed students (grade >= 4.0)
count = 0
for student in student_grades:
    if student[1] >= 4.0:
        count += 1
print('Number of passed students are: ', count)

Number of passed students are:  9


In [21]:
# length of row can be different
a = [[],
    [1],
    [2, 3],
    [4, 5, 6]]
print('length of list is: ', len(a))
print(a[3][2])
print(a[2][2]) #error

length of list is:  4
6


IndexError: list index out of range

In [41]:
# Exercise
import random as rd
# Create 2d list 5x5 of random integers
a = []
for i in range(5):
    a.append(rd.sample(range(1, 100), 5))
print(a)
# Get 3 middle rows in as many ways as you can
print(a[1:4])
print(a[-4: -1])
print(a[1: -1])
print(a[-4: 4])
count = 1
for row in a:
    if count <= 3:
        if count == 1:
            continue
    print(row)
# Get 2 last rows in as many ways as you can
print(a[3:5])
print(a[3:])
print(a[-2:])
#Enter n from keyboard, get max, min of nth row and print them
n = int(input('Enter n: '))
print(f'Max of {n} row: {max(a[n])}, min of {n} row: {min(a[n])}')
print(f'Sum of a{[n]} {sum(a[n])}')
print(f'Sorted a({n}): {sorted(a[n])}')

[[89, 69, 55, 34, 49], [64, 49, 8, 33, 32], [74, 54, 23, 20, 70], [34, 36, 86, 79, 73], [23, 20, 34, 19, 58]]
[[64, 49, 8, 33, 32], [74, 54, 23, 20, 70], [34, 36, 86, 79, 73]]
[[64, 49, 8, 33, 32], [74, 54, 23, 20, 70], [34, 36, 86, 79, 73]]
[[64, 49, 8, 33, 32], [74, 54, 23, 20, 70], [34, 36, 86, 79, 73]]
[[64, 49, 8, 33, 32], [74, 54, 23, 20, 70], [34, 36, 86, 79, 73]]
[[34, 36, 86, 79, 73], [23, 20, 34, 19, 58]]
[[34, 36, 86, 79, 73], [23, 20, 34, 19, 58]]
[[34, 36, 86, 79, 73], [23, 20, 34, 19, 58]]
Max of 3 row: 86, min of 3 row: 34
Sum of a[3] 308
Sorted a(3): [34, 36, 73, 79, 86]


In [2]:
import numpy as np
# Create array from list
a = [1, 2, 3]
b = np.array(a)
print(a, type(a))
print(b, type(b))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [45]:
# Create array from arange function (similar range function)
a = np.arange(10)
print(a)
a = np.arange(1, 10, 2) #start, end (exclusive), distance
print(a)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [63]:
# Create array from linespace(start, end (inclusive), n(number of items)) function
a = np.linspace(0, 9, 10)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [61]:
# Create array from logspace(start, end, n) function
a = np.logspace(0, 10, 11, base=2, dtype=int)
print(a)

[   1    2    4    8   16   32   64  128  256  512 1024]
0.8939966636005579


In [67]:
# Create array from 50 - 100, step 5
a = np.arange(50, 101)
print(a)
# Create 15 numbers from 2 to 5
b = np.linspace(2, 5, 15)
print(b)
# Create 10 numbers from 0 to 1
c = np.logspace(0,1,10,base=0.5)
print(c)
# Create these numbers: 3, 9, 27, 81, 243, 729, 2187, 6561, 19683, 59049
d = np.logspace(1, 10, 10, base=3, dtype=int)
print(d)

[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]
[2.         2.21428571 2.42857143 2.64285714 2.85714286 3.07142857
 3.28571429 3.5        3.71428571 3.92857143 4.14285714 4.35714286
 4.57142857 4.78571429 5.        ]
[1.         0.92587471 0.85724398 0.79370053 0.73486725 0.680395
 0.62996052 0.58326452 0.54002987 0.5       ]
[    3     9    27    81   243   729  2187  6561 19683 59049]


In [69]:
# Create arrays of zeros, ones
zeros = np.zeros(10)
print(zeros)
ones = np.ones((3, 3))
print(ones)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [72]:
# Array operations: +, -, *, /, %, //, ** with number
a = np.random.randint(10, 100, 5) #exclusive
print(a)
print(a + 10)
print(a - 10)
print(a * 10)
print(a / 10)
print(a % 10)
print(a // 10)
print(a ** 2)

[20 11 85 72 70]
[30 21 95 82 80]
[10  1 75 62 60]
[200 110 850 720 700]
[2.  1.1 8.5 7.2 7. ]
[0 1 5 2 0]
[2 1 8 7 7]
[ 400  121 7225 5184 4900]


In [73]:
# Array operators: +, -, *, /, %, //, ** with array (same size)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)
print(a // b)
print(a ** b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 2 3]
[0 0 0]
[  1  32 729]


In [3]:
# Boolean indexing
a = np.random.randint(10, 100, 10)
print(a)
print(a % 2 == 0)
b = a % 2 == 0
print(b)
print(a[b])

[30 75 53 31 82 23 81 15 61 22]
[ True False False False  True False False False False  True]
[ True False False False  True False False False False  True]
[30 82 22]


In [8]:
# Find number that has the last digit is 3
a = np.random.randint(10, 100, 10)
print(a[a % 10 == 3])
# Find number that has the first digit is 5
print(a[a // 10 == 5])

[23]
[56 54 56]


In [10]:
# 1d Array Indexing & slicing: same as list

# 2d Array Indexing & slicing
a = np.random.randint(10, 100, (5, 5))
print(a)
print(a[2][3]) #Indexing of list style
print(a[2, 3]) # Indexing of array style

[[43 86 96 70 95]
 [99 39 48 61 18]
 [59 49 64 24 66]
 [87 61 68 82 30]
 [88 28 74 82 56]]
24
24


In [11]:
# Slice rows:
print(a[1:4])


[[99 39 48 61 18]
 [59 49 64 24 66]
 [87 61 68 82 30]]


In [15]:
# Slice columns:
print(a[:, 1:3])

[[86 96]
 [39 48]
 [49 64]
 [61 68]
 [28 74]]


In [14]:
# Slice both rows and columns:
print(a[1:4, 2:4])

[[48 61]
 [64 24]
 [68 82]]


In [16]:
print(len(a), np.shape(a))

5 (5, 5)


In [22]:
b = a[0]
c = a[0:1, :]
print(b, c)
print(np.shape(b), np.shape(c))
# transpose c
d = c.T
print(d, np.shape(d))

[43 86 96 70 95] [[43 86 96 70 95]]
(5,) (1, 5)
[[43]
 [86]
 [96]
 [70]
 [95]] (5, 1)
